### ISSUE TITLE
Add Readme to your repo

### ISSUE THREAD

**Issue by Rainman21** [jonathanOak/ITS562-AWP#1]
Just exercising the issues tab -- seeing if you get an email...

Once you add a readme.md, see if you can modify it to be informative about your repo

**Comment by jonathanOak** [comment]
Issue addressed. Feel free to give it another look. Any criticism is welcomed.

**Comment by Rainman21** [comment]
NICE! just wanted to see if people were looking at their issues

Rick Sprenkle
rsprenkle@gmail.com
